name: Python SDK Build

on:
  push:
    branches: [ main ]
    paths:
      - 'python_sdk/**'
      - '!python_sdk/.github/workflows/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'python_sdk/**'
      - '!python_sdk/.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run build script
      run: |
        cd python_sdk
        chmod +x scripts/build.sh
        bash scripts/build.sh
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: python-package
        path: python_sdk/dist/ 