name: Python SDK Test

on:
  push:
    branches: [ main ]
    paths:
      - 'python_sdk/src/**'
      - 'python_sdk/tests/**'
      - 'python_sdk/scripts/test.sh'
  pull_request:
    branches: [ main ]
    paths:
      - 'python_sdk/src/**'
      - 'python_sdk/tests/**'
      - 'python_sdk/scripts/test.sh'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run test script
      run: |
        cd python_sdk
        chmod +x scripts/test.sh
        bash scripts/test.sh
    - name: Upload coverage reports
      uses: actions/upload-artifact@v3
      with:
        name: coverage-reports
        path: python_sdk/coverage.xml 