name: Python SDK Generate Stubs

on: [push, pull_request]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Run generate script
      run: |
        cd python_sdk
        chmod +x scripts/generate_stub.sh
        bash scripts/generate_stub.sh
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: generated-client-${{ matrix.python-version }}
        path: python_sdk/build/generated/ 